# Main language in use
language: python

# Python version
python:
  - '3.6'

# Ensure we have NPM in order to use Serverless
env:
  - NODE_VERSION="9"
before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
# Install dependencies
install:
  - npm i -g serverless
  - pip install boto3

# Run unit tests
script:
  - python test_handler.py
  # - serverless deploy -v

after_success:
  - sls deploy -v
