service: visits-counter

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    DYNAMO_TABLE: ${self:custom.users_table}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: '*'

functions:
  increment:
    handler: handler.increment
    events:
      - http:
          path: visits/record
          method: get
  get_counts:
    handler: handler.get_counts
    events:
      - http:
          path: visits
          method: get

resources:
  Resources:
    DynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.users_table}
        AttributeDefinitions:
          - AttributeName: visitor_id
            AttributeType: S
        KeySchema:
          - AttributeName: visitor_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  users_table: users_table
