service: visits-counter

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:*"
  #     Resource: '*'
  # environment:
  #   variable1: value1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: say/hello
          method: get

# resources:
#   Resources:
#     DynamoTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:custom.users_table}
#         AttributeDefinitions:
#           - AttributeName: cid
#             AttributeType: S
#         KeySchema:
#           - AttributeName: cid
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
