service: visits-counter

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:custom.DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: '*'

functions:
  increment:
    handler: handler.increment
    events:
      - http:
          path: visits/add
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.DYNAMODB_TABLE}

custom:
  DYNAMODB_TABLE: users_table
