service: visits-counter

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:*"
  #     Resource: '*'
  # environment:
  #   variable1: value1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: say/hello
          method: get

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
