service: cookie-counter

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  environment:
    DYNAMO_TABLE_NAME: ${self:custom.users_table}

functions:
  incrementing-cookies:
    handler: src/index.increment
    events:
      - http:
          path: cookies/increment
          method: get
  counting-cookies:
    handler: src/index.count
    events:
      - http:
          path: cookies/count
          method: get


custom:
  users_table: users_table

plugins:
  - serverless-webpack

resources:
  Resources:
    PersistanceStore:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.users_table}
        AttributeDefinitions:
          - AttributeName: cid
            AttributeType: S
          - AttributeName: number_of_visits
            AttributeType: N
        KeySchema:
          - AttributeName: cid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
